name: example
publish_to: none
version: 0.0.1
homepage: https://variance.space
repository: https://github.com/vaariance/variance-dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  variance_dart:
    path: ../

dev_dependencies:
  coverage: ^1.1.0
  lints: ^2.0.0
